### PR TITLE
Porting code to Python 3, and restructuring module

### PR DESCRIPTION
**Pull request by nlw0**
Code was converted using `2to3`, and a `setup.py` file was created. Also files were moved to fit more into a regular module structure. Compilation of C library is handled by `setuptools`. Managed to plot some subbands already!

### CODE REVIEW

**Comment by nlw0** [comment]
Hello there. I've got interested in steerable pyramids recently, started playing around with Simoncelli's original C code, and was very happy to find this more modern Python implementation in your repositories. I think I managed to update the project to Python 3, and I tried to change it to make it a library that can be installed with setuptools. This should make it a little easier to utilize the code in other projects. You might even like to think about making it available via PyPI.

**Comment by zimmerrol** [comment]
Is someone still working on this?

**Comment by nlw0** [comment]
Hi @FlashTek , I'm not actively working on this, but I would be definitely interested in doing some contribution as I consider this work something extremely important and relevant. I would imagine the original developers might have some other idea in mind instead of this PR to offer a Python3 version.

**Comment by nlw0** [comment]
Alternatively, I would love to help in a project to move the whole thing to Julia instead, the best language out there today for numerical programming.

**Pull request closed without merging**
